name: reviewdog
on: [pull_request]
jobs:
  pyflakes:
    name: runner / pyflakes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pyflakes
        uses: reviewdog/action-pyflakes@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check